name: Generate Trades

on:
  schedule:
    # run every weekday at 9:15am and 3:45pm and 11:45pm
    # EST (UTC-5)
    - cron: '15 14 * * 1-5'
    - cron: '45 20 * * 1-5'
    - cron: '45 04 * * 1-5'
    # EDT (UTC-4) in ~March-November
    # - cron: '15 13 * * 1-5'
    # - cron: '45 19 * * 1-5'
    # - cron: '45 03 * * 1-5'
  workflow_dispatch:
  

jobs:
  generate_trades:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt  

      - name: Generate trades
        run: python src/generate_trades.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/trades_morning.csv data/trades_afternoon.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Scheduled updates to trades_morning.csv and trades_afternoon.csv"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
