name: Scheduled Run

on:
    schedule:
        - cron: "0 16 * * 1-5"  # Run every weekday at 4pm

jobs:
    run-scripts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.x

            - name: Install dependencies
                run: pip install -r requirements.txt

            - name: Generate trades
                run: python generate_trades.py

                - name: Commit changes
                    run: |
                        git config --global user.name ${{ secrets.USER_NAME }}
                        git config --global user.email ${{ secrets.USER_EMAIL }}
                        git add trades_afternoon.csv trades_morning.csv
                        git commit -m "Scheduled updates to trades_afternoon.csv and trades_morning.csv"
                        git push

            - name: Execute trades
                run: python execute_trades.py
