name: Scheduled Run

on:
  push:
    branches:
      - main
  schedule:
    # Run every weekday at 9:00am EST and 4:30pm EST
    - cron: '0 14 * * 1-5'
    - cron: '30 21 * * 1-5'

jobs:
  generate_trades:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt  

      - name: Generate trades
        run: python src/generate_trades.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use the secret here

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/trades_morning.csv data/trades_afternoon.csv
          git commit -m "Scheduled updates to trades_morning.csv and trades_afternoon.csv"
          git push || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  execute_trades:
    runs-on: ubuntu-latest
    needs: generate_trades
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt  

      - name: Execute trades
        run: python src/execute_trades.py
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/trades_morning.csv data/trades_afternoon.csv
          git commit -m "Scheduled updates to trades_morning.csv and trades_afternoon.csv"
          git push || echo "No changes to commit"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
